version: "3.8"

services:
  backend:
    build: ./finalBackend
    ports:
      - "3001:3000"  # Backend exposed on 3000 inside container, mapped to 3001 on host
    volumes:
      - ./finalBackend:/app
      - /app/node_modules
    env_file:
      - ./finalBackend/.env
    depends_on:
      - mongodb
    restart: unless-stopped
    command: ["npm", "run", "dev"]

  frontend:
    build: ./finalFrontend
    ports:
      - "5173:5173"  # Frontend exposed on 5173 inside container, mapped to 5173 on host
    volumes:
      - ./finalFrontend:/app
      - /app/node_modules
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host"]

  mongodb:
    image: mongo:6
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "80:80"  
    depends_on:
      - frontend
      - backend

volumes:
  mongodb-data:
